---
title: "final_project_mkdn"
author: "Zach F"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Commit 1
```{r}
library(tidyverse)
library(rio)
library(here)
library(janitor)
demographics <- import(here("data", "Teen-Demographic-SPSS(1) copy.zip"))

phys_act <- import(here("data", "Teen-PA-SPSS(1) copy.zip"))

# joined demographics and PA-questionnaire by participant ID "PID"
joined_set <- demographics %>% full_join(phys_act, by = "PID")


# selecting only variables that we may use
selected_variables <- joined_set %>% 
  select(TAGE, TSEX, TSCHLTYPE, XTHEIGHTCM_RC, XTWEIGHTKG_RC, TETHRAC_RC, TPMPABAD, TPMPAWANT, TPMPAUPST, TPMPAIMPT, XTPREDWEEKS, XTPREDWEEKOFS, XTPREDWEEKW) %>% 

# filter to only show high school respondents & makes a new 
# column showing the time (in hours) it took the individual to
# complete the survey
highschool_only <- selected_variables %>% 
  filter(TGRADE >= 4 & TGRADE < 8) %>% 
  filter(!is.na(TGRADE)) %>% 
  mutate(survey_time_complete_in_hrs = (DATE_SUBMITTED - DATE_STARTED) / 60)

#to compress columns for start and submit time of survey
pivot_hs_only <- pivot_longer(highschool_only, 17:18, 
                              values_to = "date_and_time")
```

```{r}
5 + 4
```

